### ISSUE TITLE
Missing SimpleApi.h 

### ISSUE THREAD

**Issue by jvelilla** [rochus-keller/PeLib#1]
It seems this header is not committed.

**Comment by rochus-keller** [comment]
SimpleApi.h/cpp was an early attempt; I replaced it by ObxIlEmitter.h/cpp in the Oberon repository which separates IlEmitter from IlRenderer to support different backends. The last version of SimpleApi is in commit 5a31435003289806dfc2bd2d93a53f4245bfb250. 

EDIT: just saw your https://github.com/jvelilla/dotnet_emit/ and some other repositories; it's long time ago I met someone programming in Eiffel; last time actually when I studied with Bertrand Meyer the first two years he was at ETH Zürich; also note that I did a lot of refactoring so my version of Pelib is quite different from the original; if you need a debug info generator and a debugger interface for Mono, here is one: https://github.com/rochus-keller/MonoTools/.

**Comment by jvelilla** [comment]
Yes, I saw that you have refactored the code to make it simpler than the original code.
At the moment I'm using Windows, but I will take a look at the MonoTools, since I will need to test it on Linux too.

**Comment by rochus-keller** [comment]
Mono runs on all platforms, actually on more architectures than the Microsoft CLR, and it is written in plain C89 instead of C++. It's also much leaner. I use the Mono engine (just two files, the executable and mscorlib.dll, both < 10 MB) for my Oberon+ compiler and IDE with no Dotnet framework, just the plain CLR.
